[workspace]
members = [
    "cap2/actix-gcd",
    "cap2/gcd",
    "cap2/hello",
    "cap2/mandelbrot",
    "cap2/quickreplace",
    "cap4/ownership",
    "cap4/rust_examples",
    "cap5/references",
    "cap6",
    "cap7",
    "cap8",
]
